### ISSUE TITLE
remove god apple recipe

### ISSUE THREAD

**Issue by m1jordanallen** [m1jordanallen/1.19OceanSurvival#111]

**Comment by 4tw0ne** [comment]
As part of Bams "Golden/Enchanted Apples Healing" request, I have changed this recipe as such

2 fire res 3min
2 res 3min
2 enchanted books (any enchants)
netherite and diamond block
plus the golden apple

![Harder_Enchanted_apple](https://github.com/user-attachments/assets/98fc7c49-163e-4d68-a17f-d2ed29488985)


Known bug, JEI will not put recipe into a table for you since the enchanted books do not match explicitly. 
Does work if Manually crafting.

**Comment by 4tw0ne** [comment]
The remaining known bug listed above, affects all recipes that take 'any enchanted book'.
