### ISSUE TITLE
Fly Spawns

### ISSUE THREAD

**Issue by OmIAm** [m1jordanallen/1.19OceanSurvival#131]
421 spotted the problem with the fly spawns, or what probably was the problem.  There were a bunch of comma's left out.  Probably my fault.

config/alexsmobs/fly_spawns.json

I don't remember where you turned them off entirely at, but may be worth turning them back on.

[fly_spawns.json](https://github.com/m1jordanallen/1.19OceanSurvival/files/15396362/fly_spawns.json)

**Comment by 4tw0ne** [comment]
Just a bit to add to this...
Maggots are a bit hard to obtain this version. These are needed to be able to fight the Void Worm.

Killing a fly is the main way of obtaining these. 

Obtaining them through means of mobs like the Sugar Glider, Anteater, or Platypus, could be possible if such mobs were to actually spawn. Of which seems to be more difficult than it should (although im will to admit the potential skill issue).

If getting the flys to work in specific locations only is not possible, nor is turning up spawn chances of the above three mobs; these maggots may need to be added to some loot tables.

If able to show me how to get flys enabled, I would be happy to test further.

**Comment by 4tw0ne** [comment]
I was able to correct the issue with the fly_spawns file properly negating spawns for biomes.

The types of biomes used for ad_astra were "REGISTRY_NAME"  instead of Biome_tag.
Both of these tags can be seen in use under AlexsMobs in their file [here](https://github.com/AlexModGuy/AlexsMobs/blob/1.19/src/main/java/com/github/alexthe666/alexsmobs/config/DefaultBiomes.java) .

Here is my tested file properly negating spawns:
[fly_spawns.json](https://github.com/m1jordanallen/1.19OceanSurvival/files/15426724/fly_spawns.json)

Note: changes to this file require a full restart of Minecraft.
