### ISSUE TITLE
Remove Red Fertilizer (or make significantly more expensive to craft)

### ISSUE THREAD

**Issue by MrSelenix** [m1jordanallen/1.19OceanSurvival#72]
apparently its super op

**Comment by OmIAm** [comment]
It didn't seem that OP to me.  Maybe it's because of the mystic ag stuff he was doing?  *Shrug*

I changed it from gold nuggets to gold ingots.  

farmingforblockheads-forge-1.19.2-11.3.0\data\farmingforblockheads\recipes\red_fertilizer.json

[red_fertilizer.zip](https://github.com/m1jordanallen/1.19OceanSurvival/files/12508149/red_fertilizer.zip)

**Comment by OmIAm** [comment]
bartmantv thought that was still too cheap.  Here it is with redstone blocks, gold blocks and diamond blocks instead.

[red_fertilizer.zip](https://github.com/m1jordanallen/1.19OceanSurvival/files/12508845/red_fertilizer.zip)

**Comment by m1jordanallen** [comment]
done in 0.0.8
